events/urls.py
from django.urls import path
from . import views 
from django.conf import settings 
from django.conf.urls.static import static

urlpatterns = [
    path('', views.home, name="home" ),
    path('events', views.all_events, name="list-events"),
    path('add_venue', views.add_venue, name='add-venue'),
    path('add_event', views.add_event, name='add_event'),
    path('list_venues', views.list_venues, name="list-venues"),
    path('event_silders', views.slider_view, name="event-silders"),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

myclub_website/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('events.urls')),
    path('', include('accounts.urls')), 
]

events/models.py
from django.db import models
from django.contrib.auth.models import User

class Categories(models.Model):
    N_categorie = models.CharField(max_length=100)

    def __str__(self):
        return self.N_categorie

class Speakers(models.Model):
    N_Speakers = models.CharField(max_length=25)
    N_Categorie = models.ForeignKey(Categories, on_delete=models.CASCADE)

    def __str__(self):
        return self.N_Speakers

class Venue(models.Model):
    name = models.CharField(max_length=100, verbose_name='Venue Name')
    address = models.CharField(max_length=200)
    website = models.URLField(max_length=200)  # Use URLField for storing website URLs
    zip_code = models.CharField(max_length=10, verbose_name='ZIP Code')
    phone = models.CharField(max_length=20, verbose_name='Contact Phone')
    email_address = models.EmailField(max_length=100, verbose_name='Email Address')

    def __str__(self):
        return self.name

class MyClubUser(models.Model):
    first_name = models.CharField(max_length=100, verbose_name='First Name')
    last_name = models.CharField(max_length=100, verbose_name='Last Name')
    email = models.EmailField(max_length=100, verbose_name='Email')

    def __str__(self):
        return f"{self.first_name} {self.last_name}"
    
class Event(models.Model):
    name = models.CharField(max_length=120, verbose_name='Event Name')
    event_date = models.DateField(verbose_name='Event Date')
    categories = models.ForeignKey(Categories, on_delete=models.CASCADE)  # ForeignKey relationship with Categories model
    venue = models.ForeignKey(Venue, blank=True, null=True, on_delete=models.CASCADE)
    manager = models.ForeignKey(User, blank=True , null=True, on_delete=models.SET_NULL)
    description = models.TextField(blank=True)
    attendees = models.ManyToManyField(MyClubUser, blank=True)
    speakers = models.ForeignKey(Speakers, blank=True, null=True, on_delete=models.CASCADE)



    def __str__(self):
        return self.name

class Slider(models.Model):
    background_image = models.ImageField(upload_to='slider_images')
    title = models.CharField(max_length=100)
    subtitle = models.CharField(max_length=200)
    date_text = models.CharField(max_length=50)
    button_text = models.CharField(max_length=50)
    button_link = models.URLField()

    def __str__(self):
        return self.title


class info_event(models.Model):
    ICON_CHOICES = [
        ('ion-ios-calendar-outline', 'DATE'),
        ('ion-ios-location-outline', 'location'),
        ('ion-ios-person-outline', 'speakers'),
        ('ion-ios-pricetag-outline', 'tickets'),
    ]

    title = models.CharField(max_length=100, choices=ICON_CHOICES)
    content = models.CharField(max_length=100)

    def __str__(self):
        return f"{self.title}: {self.content}"

events/forms.py
from django import forms
from django.forms import ModelForm
from .models import Venue , Event,Categories, Speakers, info_event

# create a venue form

class VenueForm(ModelForm):
    class Meta:
        model = Venue
        fields = ('name', 'address', 'zip_code', 'phone', 'email_address')
        labels = {
            'name': '',
            'address': '',
            'zip_code': '',
            'phone': '',
            'web': '',
            'email_address': '',
        }
        widgets = {
            'name': forms.TextInput(attrs={'class':'form-control','placeholder':'Venue Name'}),
            'address': forms.TextInput(attrs={'class':'form-control','placeholder':'Address'}),
            'zip_code': forms.TextInput(attrs={'class':'form-control','placeholder':'Zip Code'}),
            'phone': forms.TextInput(attrs={'class':'form-control','placeholder':'Phone'}),
            'web': forms.TextInput(attrs={'class':'form-control','placeholder':'Website Address'}),
            'email_address': forms.TextInput(attrs={'class':'form-control','placeholder':'Email'}),
        }

class EventForm(forms.ModelForm):
    class Meta:
        model = Event
        fields = ('name','event_date', 'venue', 'manager', 'description', 'attendees', 'categories','speakers')
        labels = {
            'name' : '',
            'event_date' : '',
            'venue' : '',
            'manager' : '',
            'description' : '',
            'attendees' : '',
            'categories' : '',
            'speakers' : '',
        }
        widgets = {
            'name': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Event Name'}),
            'event_date': forms.DateInput(attrs={'class': 'form-control', 'type': 'date'}),
            'venue': forms.Select(attrs={'class': 'form-control'}),
            'manager': forms.Select(attrs={'class': 'form-control'}),
            'description': forms.Textarea(attrs={'class': 'form-control', 'placeholder': 'Description'}),
            'attendees': forms.SelectMultiple(attrs={'class': 'form-control'}),
            'categories': forms.Select(attrs={'class': 'form-control'}),
            'speakers': forms.Select(attrs={'class': 'form-control'}),
        }
class CategoriesForm(forms.ModelForm):
    class Meta:
        model = Categories
        fields = ['N_categorie']

class SpeakersForm(forms.ModelForm):
    class Meta:
        model = Speakers
        fields = ['N_Speakers', 'N_Categorie']  # Correct field name is 'Categorie'
        labels = {
            'N_Speakers': '',  # Corrected the label for 'N_Speakers'
            'N_Categorie': '',  # Corrected the label for 'Categorie'
        }


class EventInfoForm(forms.ModelForm):
    class Meta:
        model = info_event
        fields = ('title', 'content')

events/views.py
import json
from django.shortcuts import render , redirect
from .models import Event , Venue, Categories, Slider, info_event
from django.http import HttpResponse
from .forms import VenueForm , EventForm
# Create your views here.


def show_venue(request, venue_id):
    venue = Venue.objects.get(pk=venue_id)
    return render(request, 'events/show_venue.html', {'venue': venue})


def list_venues(request):
    venue_list = Venue.objects.all()
    return render(request, 'events/venue.html', {'venue_list': venue_list})

def all_events(request):
    event_list = Event.objects.all()
    List_Categorie = Categories.objects.all()
    slider_items = Slider.objects.all()
    events = info_event.objects.all()
    return render(request, 'events/event_list.html', {'event_list': event_list, 'List_Categorie' : List_Categorie, 'events': events , 'slider_items': slider_items})

def home(request):
    slider_items = Slider.objects.all()
    events = info_event.objects.all()

    return render(request, 'events/home.html', {'slider_items': slider_items, 'events': events })

def add_venue(request):
    if request.method == "POST":
        form = VenueForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('/add_venue?submitted=true')
    else:
        form = VenueForm()
    submitted = 'submitted' in request.GET
    return render(request, 'events/add_venue.html', {'form': form, 'submitted': submitted})

def add_event(request):
    if request.method == "POST":
        form = EventForm(request.POST)
        if form.is_valid():
            form.save()

            return redirect('/add_event?submitted=true')  # Redirect to the same page after successful form submission
    else:
        form = EventForm()
    submitted = 'submitted' in request.GET

    return render(request, 'events/add_event.html', {'form': form, 'submitted': submitted})

def slider_view(request):
    # Fetch all slider items from the database
    slider_items = Slider.objects.all()    
    # Pass the slider_items to the template for rendering
    return render(request, 'events/cover_slider.html', {'slider_items': slider_items})

events/templates/events/add_event.html
<!-- events/templates/events/add_event.html -->
<style>
    header{
    background: #333333;
}
.fixed-top{
    position: inherit!important;
}
.btn{
    padding: 10px!important;
}
</style>
{% extends 'events/base.html' %}
{% load static %}

{% block content %}
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-6">
            <h1 class="text-center">Add Event</h1>
            {% if submitted %}
            <div class="alert alert-success" role="alert">
                Your Event was Submitted Successfully
            </div>
            {% endif %}
            <form action="" method="POST" class="event-form">
                {% csrf_token %}
                <div class="form-group">
                    <label for="{{ form.name.id_for_label }}">Event Name</label>
                    {{ form.name }}
                </div>
                <div class="form-group">
                    <label for="{{ form.event_date.id_for_label }}">Event Date</label>
                    {{ form.event_date }}
                </div>
                <div class="title">
                    <label for="{{ form.venue.id_for_label }}" >Venue</label>
                </div>
                <div class="input-group mb-3">
                    {{ form.venue }}
                    <a href="{% url 'add-venue' %}" class="btn btn-outline-secondary" type="button" id="button-addon2">Add Another Venue</a>
                </div>
                <div class="form-group">
                    <label for="{{ form.manager.id_for_label }}">Manager</label>
                    {{ form.manager }}
                </div>
                <div class="form-group">
                    <label for="{{ form.description.id_for_label }}">Description</label>
                    {{ form.description }}
                </div>
                <div class="form-group">
                    <label for="{{ form.categories.id_for_label }}">Categories</label>
                    {{ form.categories }}
                </div>
                <div class="form-group">
                    <label for="{{ form.speakers.id_for_label }}">Speakers</label>
                    {{ form.speakers }}
                </div>
                <input type="submit" value="Submit" class="btn btn-secondary">
            </form>
        </div>
    </div>
</div>

    {% if submitted %}
    <script src="{% static 'js/timeout_msg_success.js' %}"></script>
    {% endif %}
{% endblock %}

events/templates/events/add_venue.html
{% extends 'events/base.html' %}
{% load static %}
{% block content %}

    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-6">
                <h1 class="text-center">Add Venue </h1>
                <br><br>

                {% if submitted %}
                    <div id="success-message" class="alert alert-success" role="alert">
                        Your Event was Submitted Successfully
                    </div>
                {% endif %}

                <form action="" method="POST">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <button type="submit" class="btn btn-secondary">Submit</button>
                </form>
            </div>
        </div>
    </div>
    {% if submitted %}
    <script src="{% static 'js/timeout_msg_success.js' %}"></script>
    {% endif %}
    {% endblock %}

events/templates/events/base.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="{% static 'css/home.css' %}">
    
    <!-- Bootstrap CSS -->

    <link href="static/css/bootstrap.min.css" rel="stylesheet">

  <link href="static/css/font-awesome.min.css" rel="stylesheet">
  <link href="static/css/et-line.css" rel="stylesheet">
  <link href="static/css/ionicons.min.css" rel="stylesheet">

  <link href="static/css/owl.carousel.min.css" rel="stylesheet">
  <link href="static/css/owl.theme.default.min.css" rel="stylesheet">

  <link rel="stylesheet" href="static/css/animate.min.css">

  <link href="static/css/main.css" rel="stylesheet">
  <script
    nonce="f6662d97-a7c2-47bd-8291-689f2d554250">(function (w, d) { !function (j, k, l, m) { j[l] = j[l] || {}; j[l].executed = []; j.zaraz = { deferred: [], listeners: [] }; j.zaraz.q = []; j.zaraz._f = function (n) { return function () { var o = Array.prototype.slice.call(arguments); j.zaraz.q.push({ m: n, a: o }) } }; for (const p of ["track", "set", "debug"]) j.zaraz[p] = j.zaraz._f(p); j.zaraz.init = () => { var q = k.getElementsByTagName(m)[0], r = k.createElement(m), s = k.getElementsByTagName("title")[0]; s && (j[l].t = k.getElementsByTagName("title")[0].text); j[l].x = Math.random(); j[l].w = j.screen.width; j[l].h = j.screen.height; j[l].j = j.innerHeight; j[l].e = j.innerWidth; j[l].l = j.location.href; j[l].r = k.referrer; j[l].k = j.screen.colorDepth; j[l].n = k.characterSet; j[l].o = (new Date).getTimezoneOffset(); if (j.dataLayer) for (const w of Object.entries(Object.entries(dataLayer).reduce(((x, y) => ({ ...x[1], ...y[1] })), {}))) zaraz.set(w[0], w[1], { scope: "page" }); j[l].q = []; for (; j.zaraz.q.length;) { const z = j.zaraz.q.shift(); j[l].q.push(z) } r.defer = !0; for (const A of [localStorage, sessionStorage]) Object.keys(A || {}).filter((C => C.startsWith("_zaraz_"))).forEach((B => { try { j[l]["z_" + B.slice(7)] = JSON.parse(A.getItem(B)) } catch { j[l]["z_" + B.slice(7)] = A.getItem(B) } })); r.referrerPolicy = "origin"; r.src = "/cdn-cgi/zaraz/s.js?z=" + btoa(encodeURIComponent(JSON.stringify(j[l]))); q.parentNode.insertBefore(r, q) };["complete", "interactive"].includes(k.readyState) ? zaraz.init() : j.addEventListener("DOMContentLoaded", zaraz.init) }(w, d, "zarazData", "script"); })(window, document);</script>
    <title>Hello, world!</title>
  </head>
  <body>
    {% include 'events/navbar.html' %}
    <div class="container-main">
      {% block content %}
      
      {% endblock %}
    </div>
    {% include 'events/footer.html' %}
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-geWF76RCwLtnZ8qwWowPQNguL3RmwHVBC9FhGdlKrxdiJJigb/j/68SIy3Te4Bkz" crossorigin="anonymous"></script>
    <script src="static/js/jquery.min.js"></script>
    <script src="static/js/popper.js"></script>
    <script src="static/js/bootstrap.min.js"></script>
    <script src="static/js/waypoints.min.js"></script>
    <script src="static/js/owl.carousel.min.js"></script>
    <script src="static/js/parallax.min.js"></script>
    <script src="static/js/jquery.counterup.min.js"></script>
    <script src="static/js/jquery.countdown.min.js"></script>
    <script src="static/js/wow.min.js"></script>
    <script src="static/js/main.js"></script>
    <script async src="https://www.googletagmanager.com/gtag/js?id=UA-23581568-13"></script>
    <script>
      window.dataLayer = window.dataLayer || [];
      function gtag() { dataLayer.push(arguments); }
      gtag('js', new Date());
      gtag('config', 'UA-23581568-13');
    </script>
    <script defer src="https://static.cloudflareinsights.com/beacon.min.js/v2cb3a2ab87c5498db5ce7e6608cf55231689030342039"
      integrity="sha512-DI3rPuZDcpH/mSGyN22erN5QFnhl760f50/te7FTIYxodEF8jJnSFnfnmG/c+osmIQemvUrnBtxnMpNdzvx1/g=="
      data-cf-beacon='{"rayId":"7ec5218b1b4d1221","token":"cd0b4b3a733644fc843ef0b185f98241","version":"2023.4.0","si":100}'
      crossorigin="anonymous"></script>
  </body>

</html>

events/templates/events/cover_slider.html
<style>
    
  /* Set the height of the slider section to 60vh (60% of viewport height) */
  .home-cover {
    height: 70vh;
    position: relative; /* Add position: relative to the section for proper positioning */
    overflow: hidden; /* Optional: Hide any content that might overflow */

  }

  /* Set the height of the slider content to 100% of the parent's height */
  .cover_slider,
  .cover_item,
  .slider_content,
  .slider-content-inner {
    height: 100%;
  }
  .cover_slider .cover_item .slider_content .slider-content-inner {
    vertical-align: initial;
}
</style>


<section id="home" class="home-cover">
    <div class="cover_slider owl-carousel owl-theme">
        {%for slide in slider_items %}
        <div class="cover_item" style="background-image: url(/media/{{slide.background_image}});">
            <div class="slider_content">
                <div class="slider-content-inner">
                    <div class="container">
                        <div class="slider-content-center">
                            <h2 class="cover-title">
                                {{ slide.title }}
                            </h2>
                            <strong class="cover-xl-text">{{ slide.subtitle }}</strong>
                            <p class="cover-date">
                                {{ slide.date_text }}
                            </p>
                            <a href="{{ slide.button_link }}" class=" btn btn-primary btn-rounded">
                                {{ slide.button_text }}
                            </a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        {%endfor%}
    </div>
    <div class="cover_nav">
        <ul class="cover_dots">
            <li class="active" data="0"><span>1</span></li>
            <li data="1"><span>2</span></li>
            <li data="2"><span>3</span></li>
        </ul>
    </div>
</section>
<!-- Informatiom Slider -->
<section class="pt100 pb100">
    <div class="container">
        <div class="row justify-content-center">
            {% for event in events %}
            <div class="col-6 col-md-3">
                <div class="icon_box_two">
                    <i class="{{ event.title }}"></i>
                    <div class="content">
                        <h5 class="box_title">
                            {{ event.get_title_display }}
                        </h5>
                        <p>
                            {{ event.content }}
                        </p>
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>
    </div>
</section>

events/templates/events/event_list.html
{% extends 'events/base.html' %}
{% load static %}
{% block content %}


{% include 'events/navbar.html' %}
{% include 'events/cover_slider.html' %}
<link rel="stylesheet" href="{% static 'css/event-list.css' %}">
<script src="https://kit.fontawesome.com/a2f2a18d36.js" crossorigin="anonymous"></script>
<style>
  .gray-300 {
    margin-bottom: 50px;
}
</style>

<div class="event-area gray-300">
  <div class="container position-relative pt-110">
    <div class="row">
      <div class="col-lg-12">
        <div class="background-title text-style-one">
          <h2>EVENT</h2>
        </div>
        <div class="section-head">
          <h5>Event</h5>
          <h3>Popular Event</h3>
        </div>
      </div>
    </div>
    <div class="row">
      <div class="col-lg-12">
        <div class="event-category-buttons d-flex justify-content-center">
          <ul class="nav nav-pills mb-3" id="events-tab" role="tablist">
            {% for category in List_Categorie %}
            <li class="nav-item" role="presentation">
              <button id="pills-tab{{ category.pk }}" class="nav-link {% if forloop.first %}active{% endif %}"
                data-bs-toggle="pill" data-bs-target="#pills-event{{ category.pk }}" type="button" role="tab"
                aria-controls="pills-event{{ category.pk }}"
                aria-selected="{% if forloop.first %}true{% else %}false{% endif %}">
                {{ category.N_categorie }}
                <span>{{ category.event_set.count }}</span>
              </button>
            </li>
            {% endfor %}
          </ul>
        </div>
      </div>
    </div>

    <div class="col-lg-12">
      <div class="all-event-cards">
        <div class="tab-content" id="events-tabContent">
          {% for category in List_Categorie %}
          <div class="tab-pane fade {% if forloop.first %}show active{% endif %}" id="pills-event{{ category.pk }}"
            role="tabpanel" aria-labelledby="pills-tab{{ category.pk }}">
            <div class="row">
              {% for event in category.event_set.all %}
              <div class="col-lg-4 col-md-4 wow fadeInUp animated" data-wow-delay="200ms" data-wow-duration="1500ms">
                <div class="event-card-md">
                  <!-- Your event card content here -->
                  <!-- Use event attributes like event.event_date, event.venue, event.description, etc. -->
                  <div class="event-thumb">
                    <img src="{% static 'img/event/ev-md1.png' %}" alt="">
                    <div class="event-lavel">
                      <i class="bi bi-diagram-3"></i> <span>500 Seat</span>
                    </div>
                  </div>
                  <div class="event-content">
                    <div class="event-info">
                      <div class="event-date"><a href="#"> <i class="bi bi-calendar2-week"></i>{{ event.event_date }}</a>
                      </div>
                      <div class="event-location"><a href="#"> <i class="bi bi-geo-alt"></i>{{ event.venue }}</a>
                      </div>
                    </div>
                    <h5 class="event-title"><a href="event-details.html">{{ event.description }}</a></h5>
                    <div class="event-bottom">
                      <div class="event-readme">
                        <a href="event-details.html">Book Now</a>
                      </div>
                      <div class="event-share-icons">
                        <ul class="share-options">
                          <li><a href="#"><i class="fa-brands fa-facebook-f"></i></a></li>
                          <li><a href="#"><i class="fab fa-instagram"></i></a></li>
                          <li><a href="#"><i class="fab fa-linkedin-in"></i></a></li>
                          <li><a href="#"><i class="fab fa-twitter"></i></a></li>
                        </ul>
                        <div class="share-btn"><i class="bi bi-share"></i></div>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
              {% endfor %}
            </div>
          </div>
          {% endfor %}
        </div>
      </div>
    </div>
  </div>
</div>

{% endblock %}
<script>
  // JavaScript code to set the first link as active on page load
  document.addEventListener("DOMContentLoaded", function() {
    const firstTabButton = document.querySelector("#pills-tab1");
    firstTabButton.classList.add("active");
  });
</script>

events/templates/events/footer.html
{% load static %}
<style>
  footer .footer_social li a {
    font-size: 18px;
  }
</style>

<footer>
    <div class="container">
      <div class="row justify-content-center">
        <div class="col-md-4 col-12">
          <div class="footer_box">
            <div class="footer_header">
              <div class="footer_logo">
                <img src="{% static 'img/logo.png' %}" alt="evento">
              </div>
            </div>
            <div class="footer_box_body">
              <p>
                Lorem ipsum dolor sit amet, consectetur adipiscing elit. In rhoncus massa nec gravida tempus. Integer
                iaculis in aazzzCurabitur a pulvinar nunc. Maecenas laoreet finibus lectus, at volutpat ligula euismod.
              </p>
              <ul class="footer_social">
                <li>
                  <a href="#"><i class="ion-social-pinterest"></i></a>
                </li>
                <li>
                  <a href="#"><i class="ion-social-facebook"></i></a>
                </li>
                <li>
                  <a href="#"><i class="ion-social-twitter"></i></a>
                </li>
                <li>
                  <a href="#"><i class="ion-social-dribbble"></i></a>
                </li>
                <li>
                  <a href="#"><i class="ion-social-instagram"></i></a>
                </li>
              </ul>
            </div>
          </div>
        </div>
        <div class="col-12 col-md-4">
          <div class="footer_box">
            <div class="footer_header">
              <h4 class="footer_title">
                instagram
              </h4>
            </div>
            <div class="footer_box_body">
              <ul class="instagram_list">
                <li>
                  <a href="#">
                    <img src="{% static 'img/cleander/c1.png' %}" alt="instagram">
                  </a>
                </li>
                <li>
                  <a href="#">
                    <img src="{% static 'img/cleander/c2.png' %}" alt="instagram">
                  </a>
                </li>
                <li>
                  <a href="#">
                    <img src="{% static 'img/cleander/c3.png' %}" alt="instagram">
                  </a>
                </li>
                <li>
                  <a href="#">
                    <img src="{% static 'img/cleander/c3.png' %}" alt="instagram">
                  </a>
                </li>
                <li>
                  <a href="#">
                    <img src="{% static 'img/cleander/c2.png' %}" alt="instagram">
                  </a>
                </li>
                <li>
                  <a href="#">
                    <img src="{% static 'img/cleander/c1.png' %}" alt="instagram">
                  </a>
                </li>
              </ul>
            </div>
          </div>
        </div>
        <div class="col-12 col-md-4">
          <div class="footer_box">
            <div class="footer_header">
              <h4 class="footer_title">
                subscribe to our newsletter
              </h4>
            </div>
            <div class="footer_box_body">
              <div class="newsletter_form">
                <input type="email" class="form-control" placeholder="E-Mail here">
                <button class="btn btn-rounded btn-block btn-primary">SUBSCRIBE</button>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </footer>
  <div class="copyright_footer">
    <div class="container">
      <div class="row justify-content-center">
        <div class="col-md-6 col-12">
          <p>
            Copyright &copy;
            <script>document.write(new Date().getFullYear());</script> All rights reserved | This template is made with
            <i class="fa fa-heart-o" aria-hidden="true"></i> by <a href="https://colorlib.com"
              target="_blank">Colorlib</a>
          </p>
        </div>
        <div class="col-12 col-md-6 ">
          <ul class="footer_menu">
            <li>
              <a href="#">Home</a>
            </li>
            <li>
              <a href="#">Speakers</a>
            </li>
            <li>
              <a href="#">Events</a>
            </li>
            <li>
              <a href="#">News</a>
            </li>
            <li>
              <a href="#">Contact</a>
            </li>
          </ul>
        </div>
      </div>
    </div>
  </div>

events/templates/events/navbar.html
{% load static %}
<style>

</style>
<header class="header navbar fixed-top navbar-expand-md">
  <div class="container">
    <a class="navbar-brand logo" href="#">
      <img src="{% static 'img/logo.png' %}" alt="Evento">
    </a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#headernav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="lnr lnr-text-align-right"></span>
    </button>
    <div class="collapse navbar-collapse flex-sm-row-reverse" id="headernav">
      <ul class=" nav navbar-nav menu">
        <li class="nav-item">
          <a class="nav-link active" href="#">Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link " href="#">Speakers</a>
        </li>
        <li class="nav-item">
          <a class="nav-link " href="{% url 'list-events' %}">Events</a>
        </li>
        <li class="nav-item">
          <a class="nav-link " href="#">News</a>
        </li>
        <li class="nav-item">
          <a class="nav-link " href="#">Contact</a>
        </li>
        <li class="search_btn">
          <a href="#">
            <i class="ion-ios-search"></i>
          </a>
        </li>
      </ul>
    </div>
  </div>
</header>

events/templates/events/show_venue.html
{% extends 'events/base.html' %}

{% block content %}
<center>
    <h1>{{ venue }}</h1>
    <br>
    {{ venue.address }} <br>
    {{ venue.zip_code }} <br>
    {{ venue.phone }} <br>
    {{ venue.email_address }} <br>
</center>
{% endblock %}

events/templates/events/venue.html
{% extends 'events/base.html' %}

{% block content %}
    <center>
    <h1>Venue : </h1>
    <br>
    {% for venue in venue_list %}
        <a href="{% url 'show-venue' venue.id %}">{{ venue }}</a><br>
    {% endfor %}
    </center>
{% endblock %}